"""add_command_confirmation

Revision ID: 4d9fbe0b0a7f
Revises: 9e01eb50152d
Create Date: 2026-09-08 12:35:10.503430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9fbe0b0a7f'
down_revision: Union[str, Sequence[str], None] = '9e01eb50152d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_confirmations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('command_payload', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('command_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_command_confirmations_user_id'), ['user_id'], unique=False)

    op.create_table('dynamic_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('strength', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dynamic_constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dynamic_constraints_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamic_constraints_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamic_constraints_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamic_constraints_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamic_constraints_user_id'), ['user_id'], unique=False)

    op.create_table('fixed_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fixed_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixed_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixed_events_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixed_events_user_id'), ['user_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('week_start', sa.String(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('objective_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('warnings', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_user_id'), ['user_id'], unique=False)

    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preferences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_preferences_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('preferred_days', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('energy_requirement', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('continuous_only', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('preferred_start_hour', sa.Integer(), nullable=True),
    sa.Column('preferred_end_hour', sa.Integer(), nullable=True),
    sa.Column('sleep_start', sa.Integer(), nullable=True),
    sa.Column('sleep_end', sa.Integer(), nullable=True),
    sa.Column('max_focus_block_minutes', sa.Integer(), nullable=True),
    sa.Column('daily_task_limit_minutes_weekday', sa.Integer(), nullable=True),
    sa.Column('daily_task_limit_minutes_weekend', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('plan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('previous_plan_id', sa.Integer(), nullable=True),
    sa.Column('new_plan_id', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['new_plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['previous_plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_history_user_id'), ['user_id'], unique=False)

    op.create_table('schedule_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('block_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_blocks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_blocks_user_id'), ['user_id'], unique=False)

    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('depends_on_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dependencies_depends_on_task_id'), ['depends_on_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_dependencies_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_depends_on_task_id'))

    op.drop_table('task_dependencies')
    with op.batch_alter_table('schedule_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_blocks_user_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_blocks_id'))

    op.drop_table('schedule_blocks')
    with op.batch_alter_table('plan_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_plan_history_id'))

    op.drop_table('plan_history')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_title'))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_preferences_key'))
        batch_op.drop_index(batch_op.f('ix_preferences_id'))

    op.drop_table('preferences')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_plans_id'))

    op.drop_table('plans')
    with op.batch_alter_table('fixed_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixed_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_fixed_events_title'))
        batch_op.drop_index(batch_op.f('ix_fixed_events_id'))

    op.drop_table('fixed_events')
    with op.batch_alter_table('dynamic_constraints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dynamic_constraints_user_id'))
        batch_op.drop_index(batch_op.f('ix_dynamic_constraints_type'))
        batch_op.drop_index(batch_op.f('ix_dynamic_constraints_scope'))
        batch_op.drop_index(batch_op.f('ix_dynamic_constraints_id'))
        batch_op.drop_index(batch_op.f('ix_dynamic_constraints_enabled'))

    op.drop_table('dynamic_constraints')
    with op.batch_alter_table('command_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_command_confirmations_user_id'))

    op.drop_table('command_confirmations')
    # ### end Alembic commands ###
