"""Add DynamicConstraint

Revision ID: 9e01eb50152d
Revises: dc31b9c5f9fa
Create Date: 2026-09-08 12:14:40.066836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e01eb50152d'
down_revision: Union[str, Sequence[str], None] = 'dc31b9c5f9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('strength', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dynamic_constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dynamic_constraints_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamic_constraints_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamic_constraints_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamic_constraints_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamic_constraints_user_id'), ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_constraints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dynamic_constraints_user_id'))
        batch_op.drop_index(batch_op.f('ix_dynamic_constraints_type'))
        batch_op.drop_index(batch_op.f('ix_dynamic_constraints_scope'))
        batch_op.drop_index(batch_op.f('ix_dynamic_constraints_id'))
        batch_op.drop_index(batch_op.f('ix_dynamic_constraints_enabled'))

    op.drop_table('dynamic_constraints')
    # ### end Alembic commands ###
