"""add calendar integration models

Revision ID: b17804177650
Revises: c4a2292c442c
Create Date: 2026-09-10 21:48:58.857656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17804177650'
down_revision: Union[str, Sequence[str], None] = 'c4a2292c442c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connected_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_account_id', sa.String(), nullable=False),
    sa.Column('access_token_encrypted', sa.String(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_token', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    with op.batch_alter_table('connected_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connected_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connected_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('external_event_id', sa.String(), nullable=False),
    sa.Column('recurring_event_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['connected_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'external_event_id', name='uq_account_external_event')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_external_event_id'), ['external_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_recurring_event_id'), ['recurring_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_start_time'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_recurring_event_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_external_event_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_end_time'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_account_id'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('connected_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connected_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_connected_accounts_id'))

    op.drop_table('connected_accounts')
    # ### end Alembic commands ###
