"""Phase 6 Additions

Revision ID: dc31b9c5f9fa
Revises: c43b0abcc6a7
Create Date: 2026-09-07 23:46:02.790661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc31b9c5f9fa'
down_revision: Union[str, Sequence[str], None] = 'c43b0abcc6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('depends_on_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dependencies_depends_on_task_id'), ['depends_on_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy_requirement', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('continuous_only', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('continuous_only')
        batch_op.drop_column('created_at')
        batch_op.drop_column('energy_requirement')

    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_dependencies_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_depends_on_task_id'))

    op.drop_table('task_dependencies')
    # ### end Alembic commands ###
